#!/usr/bin/env python

import sys
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from src.util import GetiRODSSession
from src.manage_acl import PermissionManager


desc = """Restores the 'own' access type of the originator user to the iRODS
path that does nor any permissions on. When the command is used recursively 
(with -r/--recursive flag), it restores the 'own' access type of the originator
user to each object (collection or data object) that dont have any avaliable permission. 

Example:
iacl-restore /tempZone/home/rods/data_object
iacl-restore /tempZone/home/rods/collection_A
iacl-restore -z tempZone
"""

if len(sys.argv) < 2:
    print('You need to specify an option/argument/parameter!')
    print('Check iacl-restore --help or -h for more information.')
    sys.exit()

arg_parser = ArgumentParser(description=desc,
                            formatter_class=RawDescriptionHelpFormatter)

arg_parser.add_argument('args', nargs='?',
                        help='Provide an absolute iRODS path - collection or data object')

arg_parser.add_argument('-z', '--zone',
                        help='Looks for all sub items (collections, data objects) of the zone to original \
                              owner access to each object that does not have a permission on.')

args = arg_parser.parse_args()

def check_object_type(session, path):
    """A function to check the path type given"""
    result_path = dict()
    if session.collections.exists(path):
        result_path['coll_path'] = path
    if session.data_objects.exists(path):
        result_path['obj_path'] = path
    return result_path

with GetiRODSSession() as session:

    if args.zone == session.zone:
        permission_check = PermissionManager(session)
        permission_check.restore_original_owner(zone_name=session.zone)
    else:
        path_type = check_object_type(session, args.args)
        for item in path_type.keys():
            if item == 'coll_path':
                permission_check = PermissionManager(session)
                permission_check.restore_original_owner(collection_path=args.args)

            if item == 'obj_path':
                permission_check = PermissionManager(session)
                permission_check.restore_original_owner(data_obj_path=args.args)
