#!/usr/bin/env python

import sys
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from src.util import GetiRODSSession
from src.manage_acl import PermissionManager


desc = """Saves all ACLs of an iRODS collection path into
the specified file format. This file will be written in the
local file system directory what the '-l' or '--location' flag
reads as an input. Keep in mind that it works only for 
collections and recursively.

Example:
iacl-save /tempZone/home/rods -l /home/user -f csv
iacl-save /tempZone/home/group_A --location /tmp --format json
"""

if len(sys.argv) < 2:
    print('You need to specify an option/argument/parameter!')
    print('Check iacl-save --help or -h for more information.')
    sys.exit()

arg_parser = ArgumentParser(description=desc,
                            formatter_class=RawDescriptionHelpFormatter)

arg_parser.add_argument('args', nargs='?',
                        help='Provide an absolute iRODS path - collection')

arg_parser.add_argument('-l', '--location',
                        help='Specifies the directory where the file will be written.')

arg_parser.add_argument('-f', '--format',
                        help='Specifies the file format in which the command will write the ACLs of a given iRODS collection.')

args = arg_parser.parse_args()

with GetiRODSSession() as session:

    if args.args and args.location and args.format:
        permission_check = PermissionManager(session)
        permission_check.save_acl(args.args, args.location, format=args.format)