#!/usr/bin/env python

from argparse import ArgumentParser, RawDescriptionHelpFormatter
from src.util import GetiRODSSession
from src.manage_acl import PermissionManager


desc = """Compare permissions(ACL) of two iRODS paths (collections or data objects)
by listing permissions attached to them.
If paths provided represent collections, then it shows inheritance as bolean.
When -r flag is used then it only shows recursively permissions of collections
themself and their sub collections.

Example:
iacl-compare -s /tempZone/home/rods -t /tempZone/home/bob
iacl-compare -sr /tempZone/home/rods/coll_A -tr /tempZone/home/bob/coll_B
"""

arg_parser = ArgumentParser(description=desc,
                            formatter_class=RawDescriptionHelpFormatter)

arg_parser.add_argument('-s', '--source',
                        help='Lists permission(ACL) types existed on an iRODS path to compare with a target path. \
                              Lists only for a given collection and its data objects, including ACLs and inheritance')

arg_parser.add_argument('-t', '--target',
                        help='Lists permission(ACL) types existed on an iRODS path to compare with a source path. \
                              Lists only for a given collection and its data objects, including ACLs and inheritance')

arg_parser.add_argument('-sr', '--source_recursive',
                        help='Lists permission(ACL) types existed on an iRODS path recursively. Lists only for collections,\
                              including ACLs and inheritance')
arg_parser.add_argument('-tr', '--target_recursive',
                        help='Lists permission(ACL) types existed on an iRODS path recursively. Lists only for collections,\
                              including ACLs and inheritance')

args = arg_parser.parse_args()

with GetiRODSSession() as session:
    if args.source and args.target:
        permission_compare_recursive = PermissionManager(session)
        permission_compare_recursive.compare_acl_of_two_collections(
                                        args.source, args.target)

    if args.source_recursive and args.target_recursive:
        permission_compare_recursive = PermissionManager(session)
        permission_compare_recursive.compare_acl_of_two_collections_recursively(
                                        args.source_recursive, args.target_recursive)